- name: Install Podman packages
  ansible.builtin.package:
    name: "{{ utils_podman_service_packages }}"
    state: installed

# - name: Deploy containers configuration
#   ansible.builtin.template:
#     src: containers.conf.j2
#     dest: /etc/containers/containers.conf
#   notify:
#     - restart podman

- name: Enable Podman service
  ansible.builtin.service:
    name: podman
    state: started
    enabled: yes
    
