name: Ansible Galaxy

on:
  push

jobs:
  publish-to-galaxy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup python
       uses: actions/setup-python@v2
       with:
         python-version: 3.9
     - name: Install ansible
       run: |
         python -m pip install --upgrade pip
         python -m pip install ansible
     - name: Run ansible galaxy build
       run: |
         ansible-galaxy collection build
